services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ryangibson
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shrk
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: